export const languages: { [key: string]: any } = {
  en: {
    language: "English",
    welcome: "Welcome to AgriAssist",
    getStarted: "Get Started",
    login: "Login",
    signUp: "Sign Up",
    username: "Username",
    password: "Password",
    selectCropType: "Select Crop Type",
    selectCropTypePlaceholder: "Select crop type",
    fruit: "Fruit",
    vegetable: "Vegetable",
    next: "Next",
    selectYourCrop: "Select Your Crop",
    selectSoilType: "Select Your Soil Type",
    getMedicines: "Get Medicines",
    medicinesAvailable: "This page will show available medicines for the recommended pesticides.",
    home: "Home",
    newsletters: "Newsletters",
    yourCrops: "Your Crops",
    profile: "Profile",
    weatherAnalysisTitle: "Weather Analysis & Image Upload",
    currentLocationTitle: "Current Location",
    fetchingLocation: "Fetching location...",
    currentWeatherTitle: "Current Weather",
    temperature: "Temperature",
    conditions: "Conditions",
    humidity: "Humidity",
    windSpeed: "Wind Speed",
    fetchingWeather: "Fetching weather...",
    leafImageTitle: "Leaf Image",
    leafImageAlt: "Leaf Image",
    takePicture: "Take Picture",
    cameraAccessRequiredTitle: "Camera Access Required",
    cameraAccessRequiredDescription: "Please allow camera access to use this feature.",
    captureImage: "Capture Image",
    locationAccessDeniedTitle: "Location Access Denied",
    locationAccessDeniedDescription: "Please enable location permissions in your browser settings to use this app.",
    geolocationNotSupportedTitle: "Geolocation Not Supported",
    geolocationNotSupportedDescription: "Your browser does not support geolocation.",
    analysisFailedTitle: "Analysis Failed",
    analysisFailedDescription: "There was an error analyzing your crop. Please try again.",
    missingDataTitle: "Missing Information",
    missingDataDescription: "Please upload a leaf image and ensure weather data is available.",
    analyzing: "Analyzing...",
    analyze: "Analyze",
    locationNameTitle: "Location Name",
    locationNamePlaceholder: "Enter location name",
    unknownLocation: "Unknown location",
      selectYourSoilType: "Select Your Soil Type",
  },
  hi: {
    language: "Hindi",
    welcome: "AgriAssist में आपका स्वागत है",
    getStarted: "शुरू करें",
    login: "लॉग इन",
    signUp: "साइन अप",
    username: "उपयोगकर्ता नाम",
    password: "पासवर्ड",
    selectCropType: "फसल का प्रकार चुनें",
    selectCropTypePlaceholder: "फसल का प्रकार चुनें",
    fruit: "फल",
    vegetable: "सब्जी",
    next: "अगला",
    selectYourCrop: "अपनी फसल का चयन करें",
    selectSoilType: "अपनी मिट्टी का प्रकार चुनें",
    getMedicines: "दवाएँ प्राप्त करें",
    medicinesAvailable: "यह पृष्ठ अनुशंसित कीटनाशकों के लिए उपलब्ध दवाएं दिखाएगा।",
    home: "होम",
    newsletters: "न्यूज़लेटर",
    yourCrops: "आपकी फसलें",
    profile: "प्रोफ़ाइल",
    weatherAnalysisTitle: "मौसम विश्लेषण और छवि अपलोड",
    currentLocationTitle: "वर्तमान स्थान",
    fetchingLocation: "स्थान प्राप्त किया जा रहा है...",
    currentWeatherTitle: "वर्तमान मौसम",
    temperature: "तापमान",
    conditions: "स्थितियाँ",
    humidity: "आर्द्रता",
    windSpeed: "हवा की गति",
    fetchingWeather: "मौसम प्राप्त किया जा रहा है...",
    leafImageTitle: "पत्ती छवि",
    leafImageAlt: "पत्ती छवि",
    takePicture: "तस्वीर लें",
    cameraAccessRequiredTitle: "कैमरा एक्सेस आवश्यक",
    cameraAccessRequiredDescription: "इस सुविधा का उपयोग करने के लिए कृपया अपने ब्राउज़र सेटिंग में कैमरा अनुमतियाँ सक्षम करें।",
    captureImage: "तस्वीर कैप्चर करें",
    locationAccessDeniedTitle: "स्थान एक्सेस अस्वीकृत",
    locationAccessDeniedDescription: "कृपया इस ऐप का उपयोग करने के लिए अपने ब्राउज़र सेटिंग में स्थान अनुमतियाँ सक्षम करें।",
    geolocationNotSupportedTitle: "भू-स्थान समर्थित नहीं है",
    geolocationNotSupportedDescription: "आपका ब्राउज़र भू-स्थान का समर्थन नहीं करता है।",
    analysisFailedTitle: "विश्लेषण विफल",
    analysisFailedDescription: "आपकी फसल का विश्लेषण करने में एक त्रुटि थी। कृपया पुन: प्रयास करें।",
    missingDataTitle: "जानकारी गुम है",
    missingDataDescription: "कृपया एक पत्ती छवि अपलोड करें और सुनिश्चित करें कि मौसम का डेटा उपलब्ध है।",
    analyzing: "विश्लेषण कर रहा है...",
    analyze: "विश्लेषण करें",
    locationNameTitle: "स्थान का नाम",
    locationNamePlaceholder: "स्थान का नाम दर्ज करें",
        unknownLocation: "अज्ञात स्थान",
      selectYourSoilType: "अपनी मिट्टी का प्रकार चुनें",
  },
  mr: {
    language: "Marathi",
    welcome: "AgriAssist मध्ये आपले स्वागत आहे",
    getStarted: "सुरू करा",
    login: "लॉग इन",
    signUp: "साइन अप",
    username: "Username",
    password: "पासवर्ड",
    selectCropType: "पिकाचा प्रकार निवडा",
    selectCropTypePlaceholder: "पिकाचा प्रकार निवडा",
    fruit: "फळ",
    vegetable: "भाजी",
    next: "पुढे",
    selectYourCrop: "आपले पीक निवडा",
    selectSoilType: "आपल्या मातीचा प्रकार निवडा",
    getMedicines: "औषधे मिळवा",
    medicinesAvailable: "हे पृष्ठ शिफारस केलेल्या कीटकनाशकांसाठी उपलब्ध औषधे दर्शवेल.",
    home: "मुख्यपृष्ठ",
    newsletters: "वृत्तपत्रे",
    yourCrops: "तुमची पिके",
    profile: "प्रोफ़ाइल",
    weatherAnalysisTitle: "हवामान विश्लेषण आणि प्रतिमा अपलोड",
    currentLocationTitle: "सध्याचे ठिकाण",
    fetchingLocation: "ठिकाण मिळवत आहे...",
    currentWeatherTitle: "सध्याचे हवामान",
    temperature: "तापमान",
    conditions: "परिस्थिती",
    humidity: "आर्द्रता",
    windSpeed: "वाऱ्याचा वेग",
    fetchingWeather: "हवामान मिळवत आहे...",
    leafImageTitle: "पानाचे चित्र",
    leafImageAlt: "पानाचे चित्र",
    takePicture: "फोटो घ्या",
    cameraAccessRequiredTitle: "कॅमेरा ऍक्सेस आवश्यक आहे",
    cameraAccessRequiredDescription: "हे वैशिष्ट्य वापरण्यासाठी कृपया आपल्या ब्राउझर सेटिंगमध्ये कॅमेरा परवानग्या सक्षम करा.",
    captureImage: "चित्र कॅप्चर करा",
    locationAccessDeniedTitle: "ठिकाण प्रवेश नाकारला",
    locationAccessDeniedDescription: "हा अॅप वापरण्यासाठी कृपया आपल्या ब्राउझर सेटिंगमध्ये स्थान परवानग्या सक्षम करा.",
    geolocationNotSupportedTitle: "भौगोलिक स्थान समर्थित नाही",
    geolocationNotSupportedDescription: "तुमचा ब्राउझर भौगोलिक स्थानाला समर्थन देत नाही.",
    analysisFailedTitle: "विश्लेषण अयशस्वी",
    analysisFailedDescription: "तुमच्या पिकाचे विश्लेषण करण्यात त्रुटी आली. कृपया पुन्हा प्रयत्न करा.",
    missingDataTitle: "माहिती गहाळ आहे",
    missingDataDescription: "कृपया पानाचे चित्र अपलोड करा आणि हवामानाचा डेटा उपलब्ध असल्याची खात्री करा.",
    analyzing: "विश्लेषण करत आहे...",
    analyze: "विश्लेषण करा",
    locationNameTitle: "ठिकाणाचे नाव",
    locationNamePlaceholder: "ठिकाणाचे नाव प्रविष्ट करा",
        unknownLocation: "अज्ञात ठिकाण",
        selectYourSoilType: "तुमच्या मातीचा प्रकार निवडा",
  },
  te: {
    language: "Telugu",
    welcome: "AgriAssist కి స్వాగతం",
    getStarted: "ప్రారంభించండి",
    login: "లాగిన్",
    signUp: "సైన్ అప్",
    username: "వినియోగదారు పేరు",
    password: "సంకేతపదం",
    selectCropType: "పంట రకాన్ని ఎంచుకోండి",
    selectCropTypePlaceholder: "పంట రకాన్ని ఎంచుకోండి",
    fruit: "పండు",
    vegetable: "కూరగాయ",
    next: "తదుపరి",
    selectYourCrop: "మీ పంటను ఎంచుకోండి",
    selectSoilType: "మీ మట్టి రకాన్ని ఎంచుకోండి",
      getMedicines: "మందులు పొందండి",
      medicinesAvailable: "ఈ పేజీ సిఫార్సు చేయబడిన పురుగుమందుల కోసం అందుబాటులో ఉన్న మందులను చూపుతుంది.",
      home: "హోమ్",
      newsletters: "వార్తాలేఖలు",
      yourCrops: "మీ పంటలు",
      profile: "ప్రొఫైల్",
      weatherAnalysisTitle: "వాతావరణ విశ్లేషణ &amp; చిత్రం అప్‌లోడ్",
      currentLocationTitle: "ప్రస్తుత స్థానం",
      fetchingLocation: "స్థానాన్ని పొందుతోంది...",
      currentWeatherTitle: "ప్రస్తుత వాతావరణం",
      temperature: "ఉష్ణోగ్రత",
      conditions: "షరతులు",
      humidity: "తేమ",
      windSpeed: "గాలి వేగం",
      fetchingWeather: "వాతావరణం పొందుతోంది...",
      leafImageTitle: "ఆకు చిత్రం",
      leafImageAlt: "ఆకు చిత్రం",
      takePicture: "చిత్రం తీయండి",
      cameraAccessRequiredTitle: "కెమెరా యాక్సెస్ అవసరం",
      cameraAccessRequiredDescription: "ఈ ఫీచర్‌ని ఉపయోగించడానికి దయచేసి మీ బ్రౌజర్ సెట్టింగ్‌లలో కెమెరా అనుమతులను ప్రారంభించండి.",
      captureImage: "చిత్రాన్ని బంధించండి",
      locationAccessDeniedTitle: "స్థాన ప్రాప్యత నిరాకరించబడింది",
      locationAccessDeniedDescription: "ఈ అనువర్తనాన్ని ఉపయోగించడానికి దయచేసి మీ బ్రౌజర్ సెట్టింగ్‌లలో స్థాన అనుమతులను ప్రారంభించండి.",
      geolocationNotSupportedTitle: "జియోలొకేషన్ మద్దతు లేదు",
      geolocationNotSupportedDescription: "మీ బ్రౌజర్ జియోలొకేషన్‌కు మద్దతు ఇవ్వదు.",
      analysisFailedTitle: "విశ్లేషణ విఫలమైంది",
      analysisFailedDescription: "మీ పంటను విశ్లేషించడంలో లోపం ఉంది. దయచేసి మళ్ళీ ప్రయత్నించండి.",
      missingDataTitle: "సమాచారం లేదు",
      missingDataDescription: "దయచేసి ఆకు చిత్రాన్ని అప్‌లోడ్ చేసి, వాతావరణ డేటా అందుబాటులో ఉందని నిర్ధారించుకోండి.",
      analyzing: "విశ్లేషిస్తోంది...",
      analyze: "విశ్లేషించండి",
      locationNameTitle: "స్థాన పేరు",
      locationNamePlaceholder: "స్థాన పేరును నమోదు చేయండి",
        unknownLocation: "తెలియని ప్రదేశం",
        selectYourSoilType: "మీ మట్టి రకాన్ని ఎంచుకోండి",
  },
};

export const crops: { [key: string]: { type: string; name: { [key: string]: string }; image: string } } = {
  papaya: {
    type: "fruit",
    name: {
      en: "Papaya",
      hi: "पपीता",
      mr: "पपई",
      te: "బొప్పాయి",
    },
    image: "https://picsum.photos/100/100",
  },
  tomato: {
    type: "vegetable",
    name: {
      en: "Tomato",
      hi: "टमाटर",
      mr: "टोमॅटो",
      te: "టొమాటో",
    },
    image: "https://picsum.photos/100/100",
  },
  // Add more crops as needed
};

export const soils: { [key: string]: { name: { [key: string]: string }; image: string } } = {
  sandy: {
    name: {
      en: "Sandy Soil",
      hi: "बलुई मिट्टी",
      mr: "वाळुची माती",
      te: "ఇసుక నేల",
    },
    image: "https://picsum.photos/100/100",
  },
  clay: {
    name: {
      en: "Clay Soil",
      hi: "चिकनी मिट्टी",
      mr: "चिकणमाती",
      te: "బంకమట్టి",
    },
    image: "https://picsum.photos/100/100",
  },
  // Add more soil types as needed
};
